### PR TITLE
Metadata

### PR DESCRIPTION
**Pull request by codealchemist**
# Changes

- Using `ytdl.getBasicInfo()` to retrieve metadata
- Using `fluent-ffmpeg` to persist metadata
  - title
  - description
  - artist
  - album
  - comment: video URL 
- Added [download](https://www.npmjs.com/package/download) package to download art
- Removed `mkdirp`
- Not using temp folder anymore, downloading to current folder
- Updated output logs
- Updated ascii art
- Added [chalk](https://www.npmjs.com/package/chalk) to prettify output
- Added [sanitize-filename](https://www.npmjs.com/package/sanitize-filename) to sanitize file names
- Updated `.gitignore` to skip mp3 and extra JSON files
- Updated test HTML file adding some styling

screenshot
screenshot

### CODE REVIEW

**Comment by duykhang53** [comment]
looks good, have you try the full youtube url with yas CLI?

**Comment by codealchemist** [comment]
> looks good, have you try the full youtube url with yas CLI?

Yeah, works too 😄 
image

**Comment by duykhang53** [comment]
You can use `ora` for progress logging https://www.npmjs.com/package/ora

**Comment by codealchemist** [comment]
@duykhang53 Just added `ora`, some colors here and there and logs with timestamps for server logging.
If you have some time to test it, please, let me know how that goes 🙌 
We need to work on better automated testing 😅

**Comment by codealchemist** [comment]
image

image

**Comment by codealchemist** [comment]
image

**Comment by codealchemist** [comment]
The updated test page:
image

**Pull request merged**
